### ISSUE TITLE
Does not support Code

### ISSUE THREAD

**Issue by AdmiringWorm** [AdmiringWorm/Faker.NET.Portable#10]
Implement methods to generate the following:
- [x] ISBN
- [x] EAN
- [x] RUT
- [x] NPI
- [x] NRIC

**Comment by supix** [comment]
Just created a pull request for ISBN10, ISBN13 and EAN.

**Comment by supix** [comment]
Is [this](https://en.wikipedia.org/wiki/National_identification_number#Chile) RUT code?
Have you pointers to NPI and NRIC, too?

**Comment by AdmiringWorm** [comment]
Truth to be told, I don't really know.
When creating this issue I was browsing the original [Ruby Faker](https://github.com/stympy/faker)
library and noticed those.
The only reference I have to go on is the following:
[RUT](https://github.com/stympy/faker/blob/master/lib/faker/code.rb#L24)
[NPI](https://github.com/stympy/faker/blob/master/lib/faker/code.rb#L6)
[NRIC](https://github.com/stympy/faker/blob/master/lib/faker/code.rb#L32)

I'm actually considering dropping those three, but haven't really made up my mind yet...

If you plan to implement those do note that I'm in the process of changing the coding style,
in that case a combination of the [EditorConfig](https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328) and [CodeMaid](https://visualstudiogallery.msdn.microsoft.com/76293c4d-8c16-4f4a-aee6-21f83a571496) Visual Studio Extensions
would be helpful in using the same style.

**Comment by AdmiringWorm** [comment]
@supix Let me know if you plan to implement RUT,NPI and NRIC and I'll assign this issue to you.
Otherwise I'll just remove them and consider this fixed when I publish the next release

**Comment by supix** [comment]
They all seem national identification numbers. In case, I might also add Italian [Fiscal Code](https://en.wikipedia.org/wiki/National_identification_number#Italy), issued to all Italian citizens at birth.

Ok as regards the new coding style. Happy to learn these tools.
