### ISSUE TITLE
Add missing documentation

### ISSUE THREAD

**Issue by AdmiringWorm** [AdmiringWorm/Faker.NET.Portable#39]
Currently some files have missing documentation (mostly missing param documentation)

**Comment by AdmiringWorm** [comment]
@supix could you think up some documentation for a couple of undocumented methods you have added?
Namely: [`GetProperty` method](https://github.com/AdmiringWorm/Faker.NET.Portable/blob/develop/src/Faker/Caching/PropertyHelper.cs#L19) in the PropertyHelper class
and the: [`GetArray` method](https://github.com/AdmiringWorm/Faker.NET.Portable/blob/develop/src/Faker/Caching/ResourceCollectionCacher.cs#L21) in the ResourceCollectionCacher class

I'm currently updating files to conform to the [StyleCop](https://stylecop.codeplex.com/) guidelines, and two of its complaints are those two methods.

**Comment by AdmiringWorm** [comment]
If you are willing to do that, please use the formatting branch I just pushed

**Comment by supix** [comment]
Ok Kim. I will do it asap. Sorry for the inconvenience.

**Comment by AdmiringWorm** [comment]
no problem, originally I planned to ignore it. But moving towards the StyleCop guildelines
I figured, it was just as well.
