### ISSUE TITLE
Is it possible langage Changing?

### ISSUE THREAD

**Issue by guhyeon** [AdmiringWorm/Faker.NET.Portable#41]
Sorry write a question at the issues.

but, I cannot find language setting.
is it possible language changing?
How can I change language?

**Comment by AdmiringWorm** [comment]
There is no feature in Faker.Net.Portable itself to change the language.
However changing the value in [Thread.CurrentThread.CurrentUICulture](https://msdn.microsoft.com/en-us/library/system.threading.thread.currentuiculture(v=vs.110).aspx) would also change the language Faker.Net.Portable uses.
